# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '$(Build.StagingDirectory)'
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(Build.StagingDirectory)'
              customCommand: 'run buildWrapper'

          
          - task: Npm@1
            inputs:
              command: publish
              publishEndpoint: 'NPM'

                    
