# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "12.x"
            displayName: "Install Node.js"

          - script: |
              npmVersionString=$(npm view kubepod version)
              echo ##vso[task.setvariable variable=tag;]$npmVersionString
            displayName: "npm set image tag"
          - task: Docker@2
            inputs:
              containerRegistry: "Dockerhub"
              repository: "adamhancock/kubepod"
              command: "buildAndPush"
              tags: $(tag)
              Dockerfile: "**/container/Dockerfile"
