# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'

          - task: Docker@2
            inputs:
              containerRegistry: "Dockerhub"
              repository: "adamhancock/kubepod"
              command: "buildAndPush"
              tags: $(imageTag)
              Dockerfile: "**/container/Dockerfile"
