# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: 'install'
          - task: Npm@1
            displayName: 'Bump version number'
            inputs:
              command: 'custom'
              customCommand: 'version patch -m "Bump version to %s [skip ci]" --force'

          - task: Npm@1
            displayName: 'Build Executables'
            inputs:
              command: 'custom'
              customCommand: 'run buildWrapper'
