# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Npm@1
            displayName: "Install dependencies"
            inputs:
              command: "install"

          - bash: |
              BUILD_NUMBER=`cat package.json | jq -r '.version'`
              fi
            env:
            BUILD_NUMBER: $(Build.BuildNumber)
            displayName: "get package version"

          - task: Npm@1
            displayName: "npm version"
            inputs:
            command: "custom"
            workingDir: $(Build.SourcesDirectory)
            verbose: false
            customCommand: "version patch --no-git-tag-version --allow-same-version"
            customRegistry: "useFeed"
            customFeed: { FEED GUID }

          - task: Npm@1
            displayName: "Build Executables"
            inputs:
              command: "custom"
              customCommand: "run buildWrapper"
